// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkpgctBOnNbC17RZa41ulKjaaM2atRQSo',
    appId: '1:276144804049:web:9a11f917c77e0408d135f0',
    messagingSenderId: '276144804049',
    projectId: 'fluttercrud-dce2f',
    authDomain: 'fluttercrud-dce2f.firebaseapp.com',
    storageBucket: 'fluttercrud-dce2f.appspot.com',
    measurementId: 'G-FXQCYEP3KD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtmuI-Jbo7EQIlL0Uev6boL87H4PdUReo',
    appId: '1:276144804049:android:a54d4cc6984c597ad135f0',
    messagingSenderId: '276144804049',
    projectId: 'fluttercrud-dce2f',
    storageBucket: 'fluttercrud-dce2f.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX_Ywve8dMr1jVn74vvDsSFuCVG2X68J4',
    appId: '1:276144804049:ios:2d3dda85ec74c7ead135f0',
    messagingSenderId: '276144804049',
    projectId: 'fluttercrud-dce2f',
    storageBucket: 'fluttercrud-dce2f.appspot.com',
    iosBundleId: 'com.example.lab',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX_Ywve8dMr1jVn74vvDsSFuCVG2X68J4',
    appId: '1:276144804049:ios:2d3dda85ec74c7ead135f0',
    messagingSenderId: '276144804049',
    projectId: 'fluttercrud-dce2f',
    storageBucket: 'fluttercrud-dce2f.appspot.com',
    iosBundleId: 'com.example.lab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkpgctBOnNbC17RZa41ulKjaaM2atRQSo',
    appId: '1:276144804049:web:9a11f917c77e0408d135f0',
    messagingSenderId: '276144804049',
    projectId: 'fluttercrud-dce2f',
    authDomain: 'fluttercrud-dce2f.firebaseapp.com',
    storageBucket: 'fluttercrud-dce2f.appspot.com',
    measurementId: 'G-FXQCYEP3KD',
  );

}